docs/guides/content/README.md
docs/guides/content/entries.md
docs/guides/content/spaces.md
docs/guides/content/types.md
docs/guides/customers/README.md
docs/guides/customers/messaging.md
docs/guides/insights/customers.md
docs/guides/insights/digital-factory.md
docs/guides/key-concepts.md
docs/guides/navigating-through-modyo.md

cambios varios textos, definiciones, palabras, etc.

Ampliación textos

---

docs/guides/content/asset-manager.md

Cambios en edición de información y subida de archivos.

cambios en asset manager

---

docs/guides/content/entries.md

código entries

---

docs/guides/content/types.md

Redefinición de Interfaz y de creación de tipos

Actualización Tipos

---

docs/.vuepress/style.styl

Se ajustó los colores, fonts y detalles de google docs, quedó beautiful

Ajuste diseño docs

---

docs/.vuepress/style.styl

habia un problema con el color de backbground, y una distancias en el home.

fix home color

---

docs/guides/customers/messaging.md
docs/guides/customers/targets.md
docs/guides/customers/users.md

corrige typos, se añaden links

corrige typos

---

docs/guides/channels/templates.md
docs/guides/content/public-api-reference.md

Documentación para integraciones con OpenID Connect

Agrega documentación para integraciones

---

docs/guides/customers/forms.md

Creé una sección de Nuevo Formulario, y dejé en la sección de la tercera tab las puras diferencias.

Revisado y reestructurado Forms #MODYO-Docs

---

docs/guides/content/asset-manager.md
docs/guides/customers/targets.md
docs/guides/platform/api.md

puntuación

---

docs/guides/README.md
docs/guides/channels/templates.md
docs/guides/content/public-api-reference.md
docs/guides/key-concepts.md
docs/guides/platform/api.md

corrección estilo Front End y Back End

Corrección término Front End

---

docs/guides/channels/templates.md
docs/guides/channels/widgets.md
docs/guides/content/entries.md
docs/guides/content/public-api-reference.md
docs/guides/content/types.md

Corrección Liquid

---

.idea/codeStyles/codeStyleConfig.xml
docs/guides/platform/team-review.md

Dejo algunas sugerencias de pequeños cambio a la redacción de la sección "Team Review"

Sugerencias redaccion seccion team review

---

.idea/codeStyles/codeStyleConfig.xml
docs/guides/platform/integration.md

Sugerencias seccion integraciones

Sugerencias seccion integraciones

---

docs/guides/content/asset-manager.md
docs/guides/content/public-api-reference.md
docs/guides/content/spaces.md

Cambios en Asset Manager, API y Spaces, de redacción.

redacción.

---

docs/guides/channels/liquid-markup.md
docs/guides/channels/widgets.md
docs/guides/commerce/README.md
docs/guides/content/asset-manager.md
docs/guides/content/entries.md
docs/guides/insights/README.md

concepto modyo

---

docs/guides/content/asset-manager.md
docs/guides/content/spaces.md
docs/guides/content/types.md
docs/guides/platform/team-review.md

Verbos textos y eliminación de reiteraciones.

---

docs/guides/content/spaces.md

cambio denominación lugar acotado. Reordenamiento sección de funciones.

cambios espacios

---

docs/guides/channels/pages.md
docs/guides/content/entries.md
docs/guides/customers/users.md

fix configuración de usuarios

---

docs/guides/content/entries.md

Se añade vista previa de múltiples sitios.

add preview

---

docs/guides/channels/widgets.md

se añade warning sobre widgets despublicados

actualizacion warning widgets

---

docs/guides/channels/widgets.md
docs/guides/content/spaces.md

se corrige texto y puntuación de widgets y espacios

reparación widgets

---

docs/guides/content/entries.md

se añade edición de entrada, cambio de propiedades, etc.

cambio entries edición

---

docs/guides/content/entries.md

se corrige estado Publicado y se amplía tip de Idiomas

estados y traducción

---

docs/guides/content/entries.md

se corrige link roto a Configuración de Sitios

link roto sitios

---

docs/guides/channels/sites.md

Se reestructura y da estilo a estados de sitios.

cambios listado estados sitios

---

docs/guides/channels/widgets.md
docs/guides/content/spaces.md

ajuste tip widgets y reescritura general spaces

ajuste widgets y spaces

---

docs/guides/channels/widgets.md

ajuste widgets restaurar

---

docs/guides/channels/liquid-markup.md
docs/guides/channels/navigation.md
docs/guides/channels/pages.md
docs/guides/channels/widgets.md
docs/guides/content/asset-manager.md
docs/guides/content/entries.md
docs/guides/content/public-api-reference.md
docs/guides/platform/README.md
docs/guides/platform/team-review.md
docs/guides/versions.md
docs/guides/whats-new.md

Cambios a presente en páginas. Eliminación verbos en futuro

---

docs/guides/channels/navigation.md
docs/guides/channels/pages.md
docs/guides/channels/sites.md

Modificación Navegación - pages- Sitios

Verbos Channels

---

docs/guides/channels/sites.md
docs/guides/channels/templates.md

tiempos verbales reparados y ortografía corregida

cambios sitios y templates

---

docs/guides/content/public-api-reference.md

cambios estilo sdk

---

docs/en/guides/customers/messaging.md
docs/guides/channels/widgets.md
docs/guides/content/public-api-reference.md

Se corrige traducción de Campañas
Se agrega Ordenar Entradas en referencia a la api

Cambios en Messaging, Widgets y API

---

docs/guides/channels/sites.md

Se agrega descripción y método de Manifiesto PWA

Manifiesto PWA

---

docs/guides/channels/sites.md

Se agrega descripción de Service Worker

Service Worker

---

docs/guides/channels/sites.md

Arreglo formato PWA

---

docs/en/platform/README.md
docs/en/platform/key-concepts.md
docs/en/platform/release-notes.md
docs/en/platform/versions.md
docs/en/platform/whats-new.md

Added missing words, corrections to translation and modified text according to common terminology

English corrections to /platform pages

---

docs/es/platform/content/entries.md
docs/platform/content/entries.md

Añade la descripción de las bulk action en entradas y añade la descripción de la eliminación de entradas

Bulk action on entries

---

docs/brand/colors.md
docs/es/brand/colors.md

Agregue grises y titulos en tabla + cambio en un hex que estaba mal

Fix colores

---

docs/.vuepress/config.js
docs/es/platform/core/roles.md
docs/es/platform/customers/README.md
docs/es/platform/customers/messaging.md
docs/es/platform/customers/profile.md
docs/es/platform/customers/realms.md
docs/es/platform/customers/targets.md
docs/es/platform/key-concepts.md
docs/es/platform/release-notes.md
docs/platform/customers/README.md
docs/platform/customers/messaging.md
docs/platform/customers/profile.md
docs/platform/customers/realms.md
docs/platform/customers/targets.md
docs/platform/key-concepts.md
docs/platform/release-notes.md

Se añade la documentación de reinos, roles y grupos en español

Adds realms, roles and groups docs

---

docs/es/platform/release-notes.md
docs/es/platform/tutorials/how-to-create-a-custom-view.md
docs/es/platform/tutorials/how-to-create-content.md
docs/es/platform/tutorials/how-to-create-home.md
docs/es/platform/tutorials/how-to-create-private-site.md

Revisión a nombres de secciones y botones. 
Usar codeblocks y <code> para mantener estandar de documentación

Revision a tutoriales y release notes

---

docs/es/platform/customers/README.md
docs/es/platform/customers/forms.md
docs/es/platform/customers/profile.md
docs/es/platform/customers/realms.md
docs/es/platform/customers/segments.md

Cambios en Customers:
- Ordenar documentación en el orden que aparece en GUI
- Spelling & grammar

Revision a customers

---

docs/es/platform/tutorials/how-to-create-a-pwa.md

Este PR incluye
- arreglo en el video de PWA que se mostraba desalineado

Centrar video

---

docs/es/resources/README.md

Este es un documento nuevo, independiente de la documentación con recursos externos a Modyo

Nueva página con recursos adicionales para desarrolladores

---

docs/es/platform/tutorials/how-to-create-a-custom-view.md
docs/es/platform/tutorials/how-to-create-a-menu.md
docs/es/platform/tutorials/how-to-create-content.md
docs/es/platform/tutorials/how-to-create-home.md
docs/es/platform/tutorials/how-to-create-private-site.md
docs/es/platform/tutorials/tutorial-seo.md

Revisión a fondo a tutoriales. 
Cambios a pasos, más info en muchas partes.
Dar más indicación en donde hacer click.

Revision a fondo a tutoriales

---

docs/.vuepress/theme/components/Home.vue
docs/en/widgets/investments/profile-survey.md

Test deployment and fix a format error

Add line to test deployment and fix a format error

---

docs/es/platform/content/public-api-reference.md
docs/es/platform/core/api.md

- Cambios a api, documentacion de paso a paso, ejemplos de curl en publicapiref
- Mas cambios a api, alerta de peligro al exponer api al publico

Pr de public-api y api.md a develop

---

docs/es/platform/channels/widgets.md
docs/es/platform/customers/profile.md
docs/es/widgets/guides/first-steps.md

1. Modificar archivo de variables de entorno en widgets y guides/first-steps
2. Mejorar documentación de tokens delegados y customers API

Mejoras a Widgets y Customers API

---

docs/.vuepress/config.js

Este PR reactiva 4 tutoriales que se encuentran ocultos y no tienen problemas tecnicos para permanecer visibles.
- Conectar Modyo con Salesforce
- Conectar Optimize para hacer A/B testing
- Personalizar Optimize
- Integracion con google Data Studio

Reactivacion de tutoriales perdidos

---

docs/es/platform/channels/drops.md

Resolves #516 
Added targets to drops documentation.  
Nota: Revisar el uso de la palabra targets/segments

Added targets to drops documentation

---

docs/es/platform/customers/segments.md
docs/es/widgets/insurance-retail/detailed-view.md
docs/es/widgets/insurance-retail/quote.md
docs/es/widgets/insurance-retail/summary.md

Docs de insurance-retail
Un cambio a una liga rota en segments.md

Documentación de widgets insurance-retail

---

docs/es/platform/core/configuration.md
docs/es/platform/core/security.md

- Cambios para agregar expiracion de sesiones
- Revision a configuration.md y security.md

Agregar doc de expiracion de sesiones

---

docs/es/platform/channels/navigation.md
docs/es/platform/channels/sites.md
docs/es/platform/content/asset-manager.md
docs/es/platform/content/entries.md
docs/es/platform/content/public-api-reference.md
docs/es/platform/content/spaces.md
docs/es/platform/content/types.md
docs/es/platform/customers/profile.md
docs/es/platform/customers/realms.md

- Este pr son todos los cambios que se realizaron para los articulos de Intercom
- 1er commit Primer review hasta Channels
- 2ndo commit Agregar sidebar depth 3 para profile y realms

review intercom

---

docs/es/platform/channels/templates.md

Agregar nuevo snippet e información pertinente. 
Agregar link hacia Liquid Markup

Agregar el nuevo snippet SEO para Modyo 9.2+

---

docs/es/platform/core/integrations/identity-providers.md

- Quitar FB y LDAP, agregar requisitos
- Agregar cambios de SAML

Cambios de SAML en sección de Identity Providers

---

docs/es/platform/core/integrations/identity-providers.md

Info validada por Marcelo, haciendo merge a master

Agregar info de URLs para SAML

---

docs/es/platform/core/integrations/identity-providers.md
docs/es/platform/core/security.md
docs/es/platform/customers/api.md
docs/es/platform/customers/realms.md

Se agrego documentación para las opciones que hacían falta de realms

Agregar cambios de config de realms

---

docs/es/platform/core/integrations/identity-providers.md
docs/es/platform/core/security.md
docs/es/platform/customers/api.md
docs/es/platform/customers/realms.md

- Realizar cambios requeridos para integracion con Azure AD

Cambios a integración con Azure

---

docs/es/dynamic/README.md
docs/es/dynamic/activation.md
docs/es/dynamic/architecture.md
docs/es/dynamic/experiences/README.md
docs/es/dynamic/experiences/retail/dashboard-payments.md
docs/es/dynamic/experiences/retail/dashboard.md
docs/es/dynamic/experiences/retail/loan-application.md
docs/es/dynamic/experiences/retail/loan-approval.md
docs/es/dynamic/experiences/retail/pay-debt.md
docs/es/dynamic/experiences/retail/product-detail.md
docs/es/dynamic/experiences/retail/transfer.md
docs/es/dynamic/integrations/README.md
docs/es/dynamic/integrations/jumio.md
docs/es/dynamic/integrations/mambu.md
docs/es/dynamic/integrations/salesforce.md
docs/es/dynamic/support.md
docs/es/dynamic/ui/README.md
docs/es/dynamic/ui/components.md
docs/es/dynamic/ui/design-kit.md

Principalmente son cambios de gramática y agregar metadata para que puedan ser encontrados por algolia.

Cambios propuestos a dynamic

---

docs/es/platform/training.md

En vez de programa de capacitación, ahora se habla de Learning Paths. Una manera dinámica en donde puedes aprender a tu ritmo.

Cambios propuestos a entrenamiento (quitar programa capacitacion)

---

docs/en/README.md

Actualización de URL. 
Cambio de "help" a "training".

MCE-318 cambio de help a training en el url

---

docs/es/platform/customers/realms.md

Agregue información de redirección posterior a login
Corrección de estilo de todo el documento
Eliminé filtros avanzados en users (no existen)
Queda pendiente verificar si existe la opción de guardar un segmento después de filtrar usuarios.

MCE-344-redirect-post-login

---

docs/es/platform/channels/sites.md
docs/es/platform/core/key-concepts.md
docs/es/platform/customers/realms.md
docs/es/platform/release-notes.md

1. Oauth to OAuth
2. liquidJS to liquidJS
3. correct ","

small fixes

---

docs/es/platform/channels/sites.md

* Added info on three new security headers 
* Reviewed for style and consistency

MCE-356 headers de seguridad

---

docs/.vuepress/theme/index.js
package-lock.json
package.json

Habilita el plugin de sitemap en la documentación, necesario para crear mejores indices en algolia.

Habilitado el sitemap

---

docs/es/platform/release-notes.md

corresctamente a correctamente

typo correction

---

docs/es/platform/content/types.md

* Added groups
* Revised according to style guide

MCE-348 documentar grupos en tipos de contenido

---

docs/es/platform/core/roles.md

Corrección de estilo y redacción
Adición de SIte viewer
Adición de Space viewer

MCE-358 documentar space y site viewer

---

docs/es/platform/release-notes.md

Actualiza release notes para version 9.2.40

Actualiza release notes para version 9.2.40

---

docs/es/platform/release-notes.md

Se agrega documentación de releases de la versión 9.2.41

release notes 9.2.41

---

docs/es/platform/customers/realms.md

Es solo uno de los tres cambios respecto a logs y eventos. Los otros dos están pendientes hasta poder ubicarlos correctamente.

MCE-370 primer cambio resumen de eventos

---

docs/es/platform/release-notes.md

Cambios destacados en releases 9.2.42 y 9.2.43

Release 9.2.42 y 9.2.43

---

docs/.vuepress/config.js
docs/en/platform/core/activity-logs.md
docs/en/platform/customers/events.md
docs/es/platform/core/activity-logs.md
docs/es/platform/customers/events.md

agrega eventos en documentacion y sidebar

MCE 370 - Agregar Events en la documentación de los reinos

---

docs/es/platform/core/security.md

Corrección de política de expiración de sesión e inactividad
Corrección de todo el documento "Seguridad"

382 - politica expiracion y mejorias doc seguridad

---

docs/es/platform/release-notes.md

Agrega notas de releases 9.2.44
Agrega fechas faltantes en releases previos

Release 9.2.44

---

docs/es/architecture/README.md

383-arquitectura

---

docs/es/architecture/why-modyo.md

revisión de documento why modyo

386 why modyo

---

docs/es/architecture/resources/README.md

revisión de documento arquitecture-resources (Aprende y participa)

387-arquitecture resources

---

docs/es/architecture/patterns/private-site.md

391 Sitio Privado - arquitectura

---

docs/es/architecture/patterns/public-site.md

Este PR recupera algunos cambios que se perdieron en el PR #612

Cambios perdidos de tonio

---

docs/es/platform/channels/navigation.md
docs/es/platform/channels/pages.md
docs/es/platform/channels/templates.md
docs/es/platform/channels/widgets.md
docs/es/platform/core/key-concepts.md
docs/es/platform/key-concepts.md

Elimina todas las apariciones de etiquetas SVG en la documentación.
Jira: https://modyohq.atlassian.net/browse/MCE-399

MCE-399 remover svg de la documentacion

---

docs/es/platform/core/key-concepts.md
docs/es/platform/customers/forms.md
docs/es/platform/insights/digital-factory.md

Elimina imagenes que usaban formato markup

MCE-436 - BULK remover imagenes

---

docs/es/platform/channels/sites.md

en el doc de sites, correcion de liga muerta a plantillas

465 correcion de link

---

docs/es/platform/content/entries.md

Eliminé todas las imágenes; sin embargo, me gustaría revisarlo completo, encontré muchos puntos de mejora.

481 eliminar imagenes y texto correspondiente

---

docs/es/architecture/patterns/microservice.md
docs/es/dynamic/README.md
docs/es/dynamic/ui/README.md
docs/es/platform/channels/navigation.md
docs/es/platform/channels/pages.md
docs/es/platform/core/integrations/identity-providers.md

Esta tarea es para solucionar errores 404 que se encontraron en el scan 
Ver mas detalles del reporte en Jira 
https://modyohq.atlassian.net/browse/MCE-475
Por favor examinar los comentarios porque algunos cambios necesitan contexto.

MCE-475 errores 404

---

docs/es/platform/release-notes.md

Agrega notas del release 9.2.53

Agrega notas del release 9.2.53

---

docs/es/platform/release-notes.md

Agrega release notes de version 9.2.54

Agrega releases de la version 9.2.54

---

docs/.vuepress/config.js
docs/en/dynamic/experiences/README.md
docs/es/dynamic/experiences/README.md

Jira:  https://modyohq.atlassian.net/browse/MCE-490

MCE-490 Crear un landing page para experiencias

---

docs/es/platform/channels/cli.md

Hola!
Les dejo el documento ya trabajado, esperando sus comentarios. 
Linda noche!

MCE-511 revision de todo el documento

---

docs/es/platform/channels/sites.md

Hola! Habían ya muchas alertas en esa pequeña seccion, no estoy segura que esta quedo en la mejor ubicacion, pero priorice que el lector no se sienta abrumado. Que opinan?

MCE-498 warning perdida de segmentos

---

docs/es/platform/channels/drops.md

Error en la tabla de user un value estaba en la fila de abajo

Error en la tabla de user drops

---

docs/es/platform/README.md

Quita saltos de líneas

---

docs/.vuepress/config.js
docs/en/platform/core/integrations/conect-modyo-salesforce.md
docs/es/README.md
docs/es/platform/core/README.md
docs/es/platform/core/integrations/conect-modyo-salesforce.md

- Restaura la sección `plataforma` ( temporalmente) en el menu lateral
- elimina apariciones de `saleforce` y la reemplaza por `salesforce`
- Actualiza enlaces a versión anterior de modyo  `platform/core` (temporal)
- actualiza enlaces en raiz de documentacion para apuntar al nuevo `basics/key-concepts`

Preparacion modyo 10

---

docs/.vuepress/config.js

English menu update

---

docs/es/platform/release-notes.md

Agrega release notes de la version 9.2.55

Release notes 9.2.55

---

docs/.vuepress/config.js
docs/es/platform/basics/Readme.md
docs/es/platform/basics/learn-modyo.md

- Se agregan enlaces e imagenes hacia los learning paths que están en intercom
- Se soluciona el problema de navegación de MCE-531 ( no se mostraba correctamente el enlace de "bienvenido a Modyo" al hacer click en "platform")
Estos dos issues se envian en el mismo PR para ahorrar tiempo porque afectan exactamente los mismos archivos.
Tareas en Jira involucradas en este PR
https://modyohq.atlassian.net/browse/MCE-531
https://modyohq.atlassian.net/browse/MCE-526

MCE-526 Agregar learning paths en aprende modyo

---

docs/en/platform/release-notes.md
docs/es/platform/release-notes.md

Documentacion release 9.2.56

---

docs/es/platform/channels/cli.md

- Actualiza el titulo para que sea mas facil de buscar
- Actualiza comandos con errores

MCE-536  Revisar y actualizar doc de CLI

---

docs/es/platform/channels/drops.md

desde custome widget hacia abajo

Drops rotos en formato

---

docs/es/platform/channels/liquid-markup/filters.md

desde zendesk llegó un ticket diciendo que estaba mal

Arreglar el Sort by

---

docs/es/platform/release-notes.md

Agrega notas del release 9.2.58

Agrega notas del release 9.2.58

---

docs/en/platform/customers/profile.md
docs/es/platform/customers/profile.md

Arregla urls al api de contenido

Arregla urls del api de customers [9.2]

---

docs/es/platform/release-notes.md

Agrega release notes de la version 9.2.60

Agrega release notes de la version 9.2.60

---

docs/es/platform/release-notes.md

release notes 9.2.61

---

docs/en/platform/release-notes.md

release note de la 9.2.62 en inglés

9.2.61 en inlgés

---

docs/es/platform/channels/cli.md

agregamos m10 como opción y por default en el .env

Modyo 10 en el documento de .env

---

docs/en/platform/release-notes.md

9.2.62 en inglés

---

docs/es/platform/release-notes.md

Agrega release notes de la version 10.0.6

release notes 10.0.6

---

docs/es/platform/release-notes.md

Release 10.0.9

---

docs/es/platform/channels/liquid-markup/filters.md

En este PR se elimina el filtro `get_session_id` reportado desactualizado por roberto

Remove Get Session ID

---

docs/es/platform/channels/sites.md
docs/es/platform/customers/messaging.md

Este PR incluye:
- Actualización en la sección de mensajería. Se separa en 2 opciones de campaña: correo y notificaciones.
- Actualización en la sección de PWA. Se menciona la nueva opción para activar webPush y se ajusta el orden para coincidir con UI.

Documentación WebPush

---

docs/es/platform/basics/Readme.md

Este PR:
- crea enlaces a las versiones anteriores de la documentacion (en español)

Enlaces a versiones anteriores de documentación

---

docs/es/platform/release-notes.md

Release 10.0.11

---

docs/es/platform/release-notes.md

release 9.2.68

---

docs/.vuepress/config.js
docs/es/platform/customers/origination.md

Este PR crea:
- Una nueva sección de originación dentro de customers 
- Un nuevo documento con las definiciones y features de origination
Este PR solo cubre la sección en español.

MCE-622 Nueva sección de Originacion ES

---

docs/.vuepress/config.js
docs/en/platform/release-notes.md

Este PR:
- agrega release notes al menu lateral en ingles y espanol
- incluye el release 10.0.12 en ingles.

Agrega Release notes al menu lateral

---

docs/es/platform/customers/forms.md

En este PR:
* Se actualiza los tipos de datos soportados en formularios para sincronizarlo con el update de Origination.
* Se agregan los tipos : `Archivo`, `País`, `Teléfono`, `Dirección` y `Grupo`.
* Se reformula el texto de los tipos para que tenga consistencia con los guidelines de documentación.
* Se elimina una alerta que se refiere a la versión 9 de Modyo (la documentación actual solo cubre la versión 10)
MISC: se eliminan automáticamente trailing spaces.

MCE-633 Actualizar tipos de datos soportados en formularios

---

docs/es/platform/customers/origination.md

No me fijé que estabamos usando mal el término originación en lugar de aplicación en unas explicaciones

Aplicaciones vs Originaciones

---

docs/es/platform/core/roles.md

Este PR:
* Agrega la opción  `Roles a medida` en el apartado de roles.
* corrige formato del documento eliminando espacios sin uso.

MCE 635 roles a medida

---

docs/en/platform/release-notes.md

10.0.17 en inglés

---

docs/es/platform/release-notes.md

Agrega notas de release 10.0.18
👀 Agrega espacios despues de los badges  para no romper el diseño del markdown 👀

Release notes 10.0.18

---

docs/es/platform/customers/messaging.md

Este PR:
Actualiza el texto para mensajes de prueba

MCE-654 - actualizacion mensaje de prueba

---

docs/en/platform/customers/messaging.md
docs/es/platform/customers/messaging.md

Este PR:
- agrega mensaje actualizado para envio de prueba.
- formato automatico de espacios y caracteres incompatibles

MCE 654 update 10.0 - mensaje de prueba EN/ES

---

docs/es/platform/customers/origination.md

This pull request includes significant updates to the `docs/es/platform/customers/origination.md` file. The main changes involve the addition of a new section on code snippets, as well as some minor improvements to existing section titles for consistency.
* **Code Snippets Section**: Added comprehensive documentation on code snippets, including their usage, properties, and interaction with APIs. This section covers:
- Introduction to code snippets and their capabilities.
- Steps to insert a code snippet.
- Detailed properties of code snippets.
- JavaScript and JSON APIs for code snippets.
- Usage of Liquid in code snippets.
- Example code snippets demonstrating practical use cases.
* **Section Title Consistency**: Updated the titles of several sections to maintain a consistent format …

Code snippets

---

docs/en/platform/release-notes.md

10.0.20.md

---

docs/en/platform/release-notes.md

release note de la nueva versión en inglés

10.0.26.md

---

docs/es/platform/customers/origination.md

agrega docu de lógica condicional

Lógica Condicional

---

docs/en/platform/release-notes.md
docs/es/platform/release-notes.md

agrega los release notes de 10.0 en español y en inglés
y la 10.1.1 en ambos idiomas también

agrega los release notes de 10.0 aglomerados en esapañol

---

docs/en/platform/customers/origination.md
docs/en/platform/customers/users.md
docs/es/platform/customers/origination.md
docs/es/platform/customers/users.md

Documentación del feature de impersonado

Impersonado
